# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'windows-2019'

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: SqlAzureDacpacDeployment@1
  displayName: 'Azure SQL DacpacTask'
  inputs:
    azureSubscription: 'Free Trial (3128b286-876c-43ac-840a-3063ff7ad107)'
    AuthenticationType: connectionString
    ConnectionString: Server=tcp:sqlserver-database-practise.database.windows.net,1433;Initial Catalog=Products;Persist Security Info=False;User ID=Ankit;Password=Data@12345;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    DacpacFile: 'D:\a\1\a\drop/SqlServerDatabase.dacpac'